import os
import json
import torch
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import torch.nn.functional as F

from agents import get_cached_knowledge_base

class GroupSemanticAnalyzer:
    """
    Computes Group Anchor Vectors (centroids) for all intents and maps their 
    geometric proximity to the destination vectors against routing performance.
    """
    def __init__(self, phase_name, corpus_path, cache_path, trace_path):
        self.phase_name = phase_name
        self.corpus_path = corpus_path
        self.cache_path = cache_path
        self.trace_path = trace_path
        
        # Load the raw corpus to map indices to Base Intent IDs
        with open(self.corpus_path, 'r', encoding='utf-8') as f:
            self.raw_data = json.load(f)
            
        # Load the cached Titan V2 embeddings generated by the pipeline
        cache = torch.load(self.cache_path, weights_only=True)
        self.embeddings = cache['t1'] # Using Turn 1 embeddings for baseline analysis
        
        # Load the master traces generated by the pipeline
        with open(self.trace_path, 'r', encoding='utf-8') as f:
            self.traces = json.load(f)

    def compute_anchors_and_metrics(self):
        """Calculates normalized centroids and maps them to performance."""
        print(f"\n--- Computing Group Anchors for {self.phase_name} ---")
        
        # 1. Calculate Group Centroids (Anchors)
        group_vectors = {}
        for i, item in enumerate(self.raw_data):
            gid = item.get("base_intent_id", item["id"])
            if gid not in group_vectors:
                group_vectors[gid] = []
            group_vectors[gid].append(self.embeddings[i].cpu().numpy())
            
        anchors = {}
        for gid, vecs in group_vectors.items():
            centroid = np.mean(vecs, axis=0)
            norm_centroid = centroid / np.linalg.norm(centroid)
            anchors[gid] = norm_centroid

        # 2. Retrieve Standard Destination Anchors (Medium Tier)
        kb = get_cached_knowledge_base("Medium")
        dest_norm = {
            "DVLA": kb["DVLA"],
            "DVSA": kb["DVSA"],
            "OOD": kb["OOD"]
        }
        
        # 3. Aggregate Performance from Traces (Filtering for a specific method, e.g., Handcrafted)
        df = pd.DataFrame(self.traces)
        df = df[df["method"].str.contains("Handcrafted_Medium", na=False)] 
        
        # Map IDs back to groups
        id_to_group = {item["id"]: item.get("base_intent_id", item["id"]) for item in self.raw_data}
        df["base_intent_id"] = df["trajectory_id"].map(id_to_group)
        
        group_stats = df.groupby("base_intent_id").agg(
            total_queries=("outcome", "count"),
            success_count=("outcome", lambda x: (x == "SR").sum()),
            abstain_count=("outcome", lambda x: (x == "SA").sum())
        ).reset_index()
        
        group_stats["Yield (DRR)"] = (group_stats["success_count"] / group_stats["total_queries"]) * 100
        group_stats["Abstention Rate"] = (group_stats["abstain_count"] / group_stats["total_queries"]) * 100

        # 4. Calculate Cosine Similarities to Destinations
        records = []
        for gid, centroid in anchors.items():
            sim_dvla = float(np.dot(centroid, dest_norm["DVLA"]))
            sim_dvsa = float(np.dot(centroid, dest_norm["DVSA"]))
            sim_ood  = float(np.dot(centroid, dest_norm["OOD"]))
            
            # Find matching performance stats
            stats = group_stats[group_stats["base_intent_id"] == gid]
            drr = stats["Yield (DRR)"].values[0] if not stats.empty else 0.0
            abstention = stats["Abstention Rate"].values[0] if not stats.empty else 0.0
            
            records.append({
                "Group": gid.replace("traj_", "").replace("_group_", " "),
                "DVLA Sim": round(sim_dvla, 3),
                "DVSA Sim": round(sim_dvsa, 3),
                "OOD Sim": round(sim_ood, 3),
                "Yield (DRR)": round(drr, 1),
                "Abstention Rate": round(abstention, 1)
            })
            
        self.analysis_df = pd.DataFrame(records).sort_values(by="Yield (DRR)", ascending=False)
        return self.analysis_df

    def plot_similarity_heatmap(self):
        """Generates a Seaborn heatmap mapping geometric proximity to yield."""
        if not hasattr(self, 'analysis_df'):
            self.compute_anchors_and_metrics()
            
        print("Generating Group Similarity Heatmap...")
        
        # Prepare data for heatmap
        heatmap_data = self.analysis_df.set_index("Group")[["DVLA Sim", "DVSA Sim", "OOD Sim"]]
        yield_data = self.analysis_df.set_index("Group")["Yield (DRR)"]
        
        # Plotting
        fig, (ax_heat, ax_yield) = plt.subplots(1, 2, figsize=(20, 12), gridspec_kw={'width_ratios': [3, 1]})
        fig.suptitle(f"{self.phase_name}: Group Anchor Proximity vs. Routing Yield", fontsize=16, fontweight='bold', y=0.98)
        
        # Similarity Heatmap
        sns.heatmap(heatmap_data, annot=True, cmap="YlGnBu", fmt=".2f", ax=ax_heat, cbar_kws={'label': 'Cosine Similarity'})
        ax_heat.set_title("Geometric Proximity to Destination Anchors", pad=15)
        ax_heat.set_ylabel("Semantic Intent Group")
        ax_heat.set_xlabel("Destination Vectors")
        
        # Yield Bar Chart aligned to the heatmap
        yield_data.plot(kind='barh', ax=ax_yield, color='#3498db', edgecolor='black')
        ax_yield.set_title("Group Yield (DRR %)", pad=15)
        ax_yield.set_xlabel("Percentage (%)")
        ax_yield.set_xlim(0, 110)
        ax_yield.invert_yaxis() # Align with heatmap ordering
        
        plt.tight_layout()
        out_path = os.path.join("results", f"{self.phase_name.replace(' ', '_')}_anchor_heatmap.png")
        plt.savefig(out_path, dpi=300)
        print(f"Heatmap successfully saved to: '{out_path}'")
        plt.close()


if __name__ == "__main__":
    os.makedirs("results", exist_ok=True)
    
    # 1. PHASE I: CLEAN BASELINE
    p1_analyzer = GroupSemanticAnalyzer(
        phase_name="Phase I Clean",
        corpus_path="data/synthetic_corpus_phase1.json",
        cache_path="cache/phase1_grouped_titan_10k_embeddings_cache.pt",
        trace_path="results/phase1_grouped_test_traces_master.json"
    )
    p1_df = p1_analyzer.compute_anchors_and_metrics()
    p1_analyzer.plot_similarity_heatmap()
    p1_df.to_csv("results/Phase_I_Group_Metrics.csv", index=False)
    
    # 2. PHASE II: ADVERSARIAL CORPUS
    p2_analyzer = GroupSemanticAnalyzer(
        phase_name="Phase II Adversarial",
        corpus_path="data/synthetic_corpus_phase2.json",
        cache_path="cache/phase2_grouped_titan_10k_embeddings_cache.pt",
        trace_path="results/phase2_grouped_test_traces_master.json"
    )
    p2_df = p2_analyzer.compute_anchors_and_metrics()
    p2_analyzer.plot_similarity_heatmap()
    p2_df.to_csv("results/Phase_II_Group_Metrics.csv", index=False)
    
    print("\n[✓] Both Phase I and Phase II Semantic Anchor Analyses Completed Successfully!")